### ISSUE TITLE
Support for multiple LTS releases

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/nodejs.org-redesign#1]
Come October we will have two LTS releases v4 and v6. The current design only support a single LTS + Current release stream. The new design should allow for 2 LTS release Lines and Current to be easily selected.

Please let me know if you would like some images or a slightly better description

**Comment by leo** [comment]
Will the number of LTS releases increase even more over time?

**Comment by ChALkeR** [comment]
@leo Accoding to the current [LTS plan](https://github.com/nodejs/LTS), the number of _active_ LTS releases will be 2 for 1 year, then will decrease back to 1 for ½ year, than will be 2 again for 1 year, and so on.

Plus one _maintenance_ LTS release (two until the end of this year) and from one to two _current_ releases. I don't suppose that we will want more than one _current_ release on the download page and/or _maintenance_ LTS releases. Or do we?

**Comment by leo** [comment]
Ahh, that's what I meant: **Active LTS releases**. Thanks for the details, @ChALkeR!

Since the current "Download" page doesn't show any maintenance releases, I'm assuming that the final one has to support **two LTS releases** (just one will also look great, of course) and **one Current release**.

**Comment by Fishrock123** [comment]
The downloads page should support this, but I'm not sure it's worth it on the frontpage.

**Comment by rvagg** [comment]
I'm also not sure how much we'll want to be banging the v4 drum after we have v6 go LTS either, we're going to have to feel this one out I think.
