### ISSUE TITLE
Consider Figma for open-source design 

### ISSUE THREAD

**Issue by athyuttamre** [nodejs/nodejs.org-redesign#3]
I wanted to ask if you would consider using Figma (www.figma.com) as the design tool for this redesign. It makes collaboration easy and files easily shareable. Further, being on the web means anyone can access it, irrespective of operating system.

Disclosure: I was a former intern there, but do believe it would fit the use case here well.

**Comment by leo** [comment]
Interesting tool, but it looks like it requires building the whole UI inside their application. I'd rather use [Invision](https://www.invisionapp.com) or [Marvel](https://marvelapp.com), because we'll create the design in Sketch.

**Comment by athyuttamre** [comment]
Thanks for the response @leo! 

Figma is a replacement for Sketch (rather than a later stage prototyping tool like Invision or Marvel). I think it aligns more with open-source since it works on all platforms and can be shared with the community. This also means developers and other community members can leave feedback on design files, which isn't currently possible unless we're posting mockups or PNGs. Essentially it allows design in the open, just as GitHub allows coding in the open. FWIW it also supports importing existing Sketch files.

Just wanted to share the tool though; ultimately your call! :)

**Comment by zeke** [comment]
Figma can import sketch files.

The desktop version is also an Electron app, so that's a bonus. ⚛️ 

cc @poiru who works at Figma and is an Electron maintainer.

**Comment by karol-depka** [comment]
Do you know if Figma has a free/promo plan for Open-source projects? I'm interested myself as well for an open-source project that I founded.

**Comment by athyuttamre** [comment]
Not that I know of, but would recommend reaching out on their website / Twitter!

**Comment by athyuttamre** [comment]
Also closing this issue since the timeline to choose tooling has probably passed.
