### ISSUE TITLE
Has there been any progress?

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org-redesign#4]
Wanted to check in here and ask: has there been any progress made on this? As Node.js is growing, I'm seeing more and more that we need an updated site - community efforts, foundation efforts, and general optimizations are all growing, and an updated site would be extremely helpful in streamlining these efforts.

**Comment by leo** [comment]
Sadly, I haven't yet managed to tackle this. We're still on a big project that needs to be released first!

**Comment by bnb** [comment]
@leo Sorry to bother you, but I'm hoping Now Desktop 2 was the big release? 😁 

We briefly discussed this in today's Community Committee meeting - given how long it's been, do you think this project will be moving forward?

**Comment by leo** [comment]
Yep, Now Desktop 2 was the big one. @evilrabbit and I will collect all the information tomorrow and start working on the fresh layout together... 😊

**Comment by bnb** [comment]
@leo Awesome. I know that both the Website WG (@nodejs/website) and the Node.js Community Committee (@nodejs/commcomm-members) are interested in this project, and are keen to get started. That said, there may need to be some further co-ordination now that Mikeal is not at the Node.js Foundation anymore 🤔

**Comment by fhemberger** [comment]
It would be nice if you could keep me in the loop. We have some design related issues in the website project, and it would be helpful for us to coordinate the general direction we're moving in.

**Comment by sotayamashita** [comment]
@bnb 

- Do you have a milestone for it?
- Who will manage the project?
