### ISSUE TITLE
Lost access

### ISSUE THREAD

**Issue by leo** [nodejs/nodejs.org-redesign#5]
Sorry, guys - I accidentally removed myself as a collaborator. Can you add me again? @MylesBorins @mikeal

**Comment by bnb** [comment]
@leo Not sure if @mikeal has access anymore. Let me see if I can help raise this for you.

**Comment by leo** [comment]
Thank you!

**Comment by leo** [comment]
Closing this now, as it seems like someone else took over... 😊
